services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nestjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - /app/node_modules
    command: npm run start:dev